#Local Storage
version: '3.8'
services:
  mc:
    image: itzg/minecraft-server
    container_name: paper
    environment:
      EULA: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 20
      MEMORY: 4G
      GID: 0
      UID: 0
    ports:
      - "25565:25565"
    volumes:
      - mc-paper:/data
    restart: unless-stopped
volumes:
    mc-paper: {}

#SMB Storrage
version: '3.8'
services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft-server
    environment:
      EULA: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 25
      MEMORY: 8G
    ports:
      - "25565:25565"
    volumes:
      - mc-paper:/data
    restart: unless-stopped
volumes:
    mc-paper:
      external: true