services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft-server
    environment:
      EULA: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 25
      MEMORY: 8G
    ports:
      - "25565:25565"
    volumes:
      - ~/volumes/mc-paper:/data
    restart: unless-stopped