- name: Get Secrets
  uses: bitwarden/sm-action@v1
  with:
    access_token: ${{ secrets.BW_ACCESS_TOKEN }}
    secrets: |
      b2c1a248-f39b-429f-afdf-b15f00ca37bb > xo-redis-pw
      bdbb16bc-0b9b-472e-99fa-af4101309076 > SECRET_NAME_2
