on: push
jobs:
  build:
    runs-on: local-runner
    steps:
      - name: Bitwarden Secrets Manager GitHub Action
        uses: bitwarden/sm-action@v1.0.0
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          secrets: |
            b2c1a248-f39b-429f-afdf-b15f00ca37bb > xo-redis-pw
